import './globals.css'
import './fonts.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/common_components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inland Marine',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
